theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Formula For A Perfect Movie
description: A website on which we present our research and analysis for the formula of a perfect movie. 
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
